version: '3.2'
services:
  db:
    build: ./db/
    volumes:
      - './db/var/:/var/lib/postgresql/data'
    ports:
      - '5432:5432' # expose ports - HOST:CONTAINER
    # expose:
    #   - '5432' # Expose ports without publishing them to the host machine
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  api:
    build: ./api/
    expose:
      - '8080' # Expose ports without publishing them to the host machine
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    links:
      - db
  web:
    build: ./web/
    volumes:
      - './web/html/:/srv/webapp/html'
    ports:
      - '${NGINX_PORT}:80' # expose ports - HOST:CONTAINER
    links:
      - api
